### ISSUE TITLE
More time cost on  figure when reproducing figure 15 on RaspberryPi 4B

### ISSUE THREAD

**Issue by ShoiLyaung** [HelloKevin07/ElasticTrainer#2]
Environment: The same OS image and code provided on [https://zenodo.org/records/7927042](url). And I followed "ElasticTrainer_AE_Appendix.pdf"
When I was reproducing the main results of figure 15ad , I tried to run `./run_figure15ad.sh`  on RaspberryPi 4B instead of Jetson TX2. And the figures showed some problem. While half of the figure presents the result perfectly, the ElasticTrainer seems to train another 10 more epoch from the 11th epoch with more time cost. However the log didn't show any message about extra 10 epoch, and it even shows the time cost of ElasticTrainer is 24.88h, which doesn't fit the figure.

RESULT: 
[Figure_15_d.pdf](https://github.com/pittisl/ElasticTrainer/files/13228345/Figure_15_d.pdf)
[Figure_15_a.pdf](https://github.com/pittisl/ElasticTrainer/files/13228347/Figure_15_a.pdf)

LOG: [run_figure15_ad.log](https://github.com/pittisl/ElasticTrainer/files/13228541/run_figure15_ad.log)

**Comment by HelloKevin07** [comment]
Thank you for your effort of reproducing our results!

This is very strange and unfortunate. Our code simply extracts the tensorboard log data, and saves it into PDF using matplotlib. **If you don't trust our code of showing the results, you could always directly check confidential results on tensorboard, see the [guide](https://github.com/pittisl/ElasticTrainer#checking-results).**

BTW, actually, a similar bug appeared on one AE reviewer's side but all other AE reviewers could generate the figures perfectly. On our side, we were unable to reproduce the reported bug at that time. Maybe it's because long time training triggers some unpredictable issues (e.g., overheat) on raspberry pi4.
